export default {
  name: 'galleryProject',
  title: 'Gallery Project',
  type: 'document',
  fields: [
    {
      name: 'title',
      title: 'Title',
      type: 'string',
      validation: (Rule) => Rule.required(),
    },
    {
      name: 'slug',
      title: 'Slug',
      type: 'slug',
      options: { source: 'title' },
      validation: (Rule) => Rule.required(),
    },
    {
      name: 'url',
      title: 'URL',
      type: 'url',
    },
    {
      name: 'seoTitle',
      title: 'SEO Title (Opcjonalnie: długa nazwa dla Google)',
      type: 'string',
      description: 'Jeśli wypełnisz, Google użyje tej nazwy zamiast krótkiego Title.',
    },
    {
      name: 'seoDescription',
      title: 'SEO Description (Opcjonalnie: długi, niewidzialny opis dla Google)',
      type: 'text',
      description: 'Niewidzialny na stronie, ale doskonały dla SEO. Pełen słów kluczowych kontekst.',
    },
    {
      name: 'description',
      title: 'Description',
      type: 'text',
      validation: (Rule) => Rule.required(),
    },
    {
      name: 'frontImage',
      title: 'Front Image (Unpainted)',
      type: 'image',
      options: { hotspot: true },
      validation: (Rule) => Rule.required(),
    },
    {
      name: 'paintedImage',
      title: 'Painted Image',
      type: 'image',
      options: { hotspot: true },
      validation: (Rule) => Rule.required(),
    },
    {
      name: 'techStack',
      title: 'Tech Stack (Wybierz z listy u dołu po kolei max 4)',
      type: 'array',
      of: [{ type: 'string' }],
      options: {
        list: [
          { title: 'React', value: 'reactlogo.webp' },
          { title: 'HTML', value: 'htmllogo.webp' },
          { title: 'CSS', value: 'csslogo.webp' },
          { title: 'JavaScript', value: 'jslogo.webp' },
          { title: 'Tailwind CSS', value: 'tailwindlogo.webp' },
          { title: 'Firebase', value: 'firebaselogo.webp' },
          { title: 'Netlify', value: 'netlifylogo.webp' },
          { title: 'WordPress', value: 'wordpresslogo.webp' },
          { title: 'Elementor', value: 'elementorlogo.webp' },
          { title: 'PHP', value: 'phplogo.webp' },
        ],
        layout: 'grid',
      },
      validation: (Rule) => Rule.max(4),
    },
  ],
};
